FROM golang:1.19 AS builder

ENV ROOT=/app/src
WORKDIR $ROOT
COPY *.go go.mod go.sum ./
COPY cmd/ ./cmd/
WORKDIR $ROOT/cmd/api
RUN GGO_ENABLED=0 GOOS=linux go build -o ./main .

FROM gcr.io/distroless/base-debian11 AS runner
WORKDIR /
COPY --from=builder /app/src/cmd/api/main ./main
USER nobody
CMD ["./main"]
