FROM golang:1.19 AS builder

WORKDIR /app
COPY *.go go.mod go.sum ./
COPY cmd/ ./cmd/
RUN cd cmd/api; GGO_ENABLED=0 GOOS=linux go build -o /app/main 
CMD ["/app/main"]

# FROM debian:buster-slim AS runner
# COPY --from=builder /app/main /main
# USER nobody
# CMD ["./main"]
